### PR TITLE
Skip not present CI tests

### LINKED ISSUE #112: no cluster_loader/ci_test.sh
causes CI to fail.   For example, see [this log error](http://perf-sm5039-4-8.perf.lab.eng.rdu2.redhat.com:8080/job/snafu_jjb/25/consoleFull)

### PR DESCRIPTION
**Pull request by rsevilla87**
Non existing tests, like cluster loader, breaks CI. Skip them if they doesn't exist.

Closes #112

### CODE REVIEW

**Comment by aakarshg** [comment]
ok to test

File: ci/run_ci.sh [hunk 1]
```diff
@@ -46,7 +46,7 @@ do
   start_time=`date`
   my_dir=${dir::-1}
   figlet "CI test for "$my_dir
-  if $my_dir/ci_test.sh
+  if [ -f $my_dir/ci_test.sh ] && $my_dir/ci_test.sh
```
Comment (aakarshg) [inline ci/run_ci.sh]: just this change alone will still cause failures in CI as the rc is set in else part. Unless im reading this wron

Comment (rsevilla87) [reply ci/run_ci.sh]: You're right! I pushed some changes fixing this
